{
 "title": "Dashboard Juegos Florales",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Total de Equipos",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "parsedQuery": "db.Equipo.aggregate([{\"$count\":\"total\"}])",
     "query": "db.Equipo.aggregate([{$count: \"total\"}])"
    }
   ]
  },
  {
   "title": "Total de Participantes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "query": "db.Equipo.aggregate([{$group: {_id: null, count: {$sum: {$size: \"$Participantes\"}}}}, {$project: {_id: 0, count: 1}}])"
    }
   ]
  },
  {
   "title": "Distribución de Tipos de Eventos",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "parsedQuery": "db.Evento.aggregate([{\"$group\":{\"_id\":\"$Tipo\",\"count\":{\"$sum\":1}}},{\"$project\":{\"Tipo\":\"$_id\",\"count\":1,\"_id\":0}}])",
     "query": "db.Evento.aggregate([{$group: {_id: \"$Tipo\", count: {$sum: 1}}}, {$project: {Tipo: \"$_id\", count: 1, _id: 0}}])"
    }
   ]
  },
  {
   "title": "Equipos y Participantes",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "query": "db.Equipo.find({}, {Nombre: 1, \"Participantes.Nombre\": 1, _id: 0})"
    }
   ]
  }
 ]
}