name: infracost-analysis

on:
  workflow_dispatch: # Permite disparar manualmente el flujo
    branches:
      - main

jobs:
  analyze-cost:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Checkout del código del repositorio
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          repository: UPT-FAING-EPIS/proyecto-si8811a-2024-ii-u1-desarrollo-api-back
          ref: main

      # Paso 2: Instalar AWS CLI
      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli

      # Paso 3: Instalar Terraform
      - name: Install Terraform
        run: |
          wget -O - https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
          sudo apt update && sudo apt install -y terraform

      # Paso 4: Configurar las credenciales de AWS
      - name: Configure AWS credentials
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set region us-east-1

      # Paso 5: Verificar la conexión a AWS
      - name: Verify AWS connectivity
        run: aws sts get-caller-identity

      # Paso 6: Inicializar Terraform
      - name: Initialize Terraform
        run: |
          terraform init

      # Paso 7: Validar la configuración de Terraform
      - name: Validate Terraform configuration
        run: |
          terraform validate

      # Paso 8: Generar el plan de Terraform
      - name: Generate Terraform Plan
        run: |
          terraform plan -out=tfplan
          terraform show -json tfplan > tfplan.json

      # Paso 9: Instalar Infracost
      - name: Install Infracost
        run: |
          curl -fsSL https://raw.githubusercontent.com/infracost/infracost/master/scripts/install.sh | sh
          infracost configure set api_key ${{ secrets.INFRACOST_API_KEY }}
          infracost configure set currency USD

      # Paso 10: Generar desglose de costos
      - name: Generate Infracost Breakdown
        run: |
          infracost breakdown --path=tfplan.json --format json --out-file infracost.json

      # Paso 11: Mostrar informe de costos
      - name: Display Cost Reports
        run: |
          infracost output --path=infracost.json --format table > infracost_monthly.txt
          cat infracost_monthly.txt

      # Paso 12: Subir informes como artefactos
      - name: Upload Cost Reports
        uses: actions/upload-artifact@v3
        with:
          name: infracost-reports
          path: |
            infracost.json
            infracost_monthly.txt

      # Paso 13: Limpiar credenciales de AWS (opcional)
      - name: Cleanup AWS credentials
        run: |
          unset AWS_ACCESS_KEY_ID
          unset AWS_SECRET_ACCESS_KEY
          unset AWS_SESSION_TOKEN
