name: Terraform Test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    name: Run Terratest
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: us-east-1

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: '1.5.0'

      - name: Prepare test directory
        run: |
          mkdir -p test
          cp Test/* test/ || true

      - name: Setup Go environment
        working-directory: ./test
        run: |
          rm -f go.mod go.sum
          go mod init terraform-test
          go mod tidy

      - name: Run Terratest
        working-directory: ./test
        run: go test -v -timeout 30m
